name: oneai
description: A comprehensive mobile AI chatbot application that integrates multiple AI providers into a single, user-friendly interface with local and cloud storage capabilities.

# Prevent publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# Dart SDK version constraints
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

# Main dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.1

  # Network & HTTP
  http: ^1.1.2

  # Storage & Persistence
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  crypto: ^3.0.3

  # Configuration
  flutter_dotenv: ^5.1.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# Flutter configuration
flutter:
  uses-material-design: true